# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_add_tuition_record.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 498)
        Dialog.setMinimumSize(QtCore.QSize(640, 498))
        Dialog.setMaximumSize(QtCore.QSize(640, 498))
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 618, 591))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 0, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 1, 2, 1, 1)
        self.comboBox_1 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_1.setFont(font)
        self.comboBox_1.setObjectName("comboBox_1")
        self.gridLayout.addWidget(self.comboBox_1, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 0, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lcdNumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setObjectName("lcdNumber")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lcdNumber)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.dateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox_3 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.timeEdit = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timeEdit.setFont(font)
        self.timeEdit.setWrapping(False)
        self.timeEdit.setSpecialValueText("")
        self.timeEdit.setObjectName("timeEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.timeEdit)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox.setFont(font)
        self.spinBox.setMaximum(300)
        self.spinBox.setSingleStep(15)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setPrefix("")
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.spinBox_2 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_2.setFont(font)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_2)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_3.setFont(font)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_3)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_4.setFont(font)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_4)
        self.horizontalLayout_2.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setSpacing(6)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.comboBox_10 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_10.setFont(font)
        self.comboBox_10.setObjectName("comboBox_10")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_10)
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.comboBox_11 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_11.setFont(font)
        self.comboBox_11.setObjectName("comboBox_11")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_11)
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.comboBox_12 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_12.setFont(font)
        self.comboBox_12.setObjectName("comboBox_12")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_12)
        self.label_29 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_7.setFont(font)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_7)
        self.label_30 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.comboBox_13 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_13.setFont(font)
        self.comboBox_13.setObjectName("comboBox_13")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_13)
        self.label_31 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.comboBox_14 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_14.setFont(font)
        self.comboBox_14.setObjectName("comboBox_14")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_14)
        self.label_32 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_8.setFont(font)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_8)
        self.label_33 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.comboBox_15 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_15.setFont(font)
        self.comboBox_15.setObjectName("comboBox_15")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.comboBox_15)
        self.label_34 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.totalCostLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.totalCostLabel.setObjectName("totalCostLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.totalCostLabel)
        self.totalCostDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.totalCostDoubleSpinBox.setObjectName("totalCostDoubleSpinBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.totalCostDoubleSpinBox)
        self.horizontalLayout_2.addLayout(self.formLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pButton_Add_more = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pButton_Add_more.setObjectName("pButton_Add_more")
        self.horizontalLayout.addWidget(self.pButton_Add_more)
        self.pButton_Add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pButton_Add.setFont(font)
        self.pButton_Add.setObjectName("pButton_Add")
        self.horizontalLayout.addWidget(self.pButton_Add)
        self.pButton_Cancel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pButton_Cancel.setFont(font)
        self.pButton_Cancel.setObjectName("pButton_Cancel")
        self.horizontalLayout.addWidget(self.pButton_Cancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_23.setBuddy(self.comboBox_1)
        self.label_25.setBuddy(self.comboBox_2)
        self.label_24.setBuddy(self.comboBox_1)
        self.label.setBuddy(self.lineEdit)
        self.label_2.setBuddy(self.lineEdit)
        self.label_4.setBuddy(self.dateEdit)
        self.label_6.setBuddy(self.comboBox_3)
        self.label_7.setBuddy(self.timeEdit)
        self.label_8.setBuddy(self.spinBox)
        self.label_9.setBuddy(self.doubleSpinBox)
        self.label_10.setBuddy(self.spinBox_2)
        self.label_12.setBuddy(self.doubleSpinBox_2)
        self.label_11.setBuddy(self.doubleSpinBox_3)
        self.label_13.setBuddy(self.doubleSpinBox_4)
        self.label_26.setBuddy(self.comboBox_10)
        self.label_27.setBuddy(self.comboBox_11)
        self.label_28.setBuddy(self.comboBox_12)
        self.label_29.setBuddy(self.doubleSpinBox_7)
        self.label_30.setBuddy(self.comboBox_13)
        self.label_31.setBuddy(self.comboBox_14)
        self.label_32.setBuddy(self.doubleSpinBox_8)
        self.label_33.setBuddy(self.comboBox_15)
        self.label_34.setBuddy(self.lineEdit_3)

        self.retranslateUi(Dialog)
        self.pButton_Cancel.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.comboBox_1, self.comboBox_2)
        Dialog.setTabOrder(self.comboBox_2, self.lineEdit)
        Dialog.setTabOrder(self.lineEdit, self.dateEdit)
        Dialog.setTabOrder(self.dateEdit, self.comboBox_3)
        Dialog.setTabOrder(self.comboBox_3, self.timeEdit)
        Dialog.setTabOrder(self.timeEdit, self.spinBox)
        Dialog.setTabOrder(self.spinBox, self.doubleSpinBox)
        Dialog.setTabOrder(self.doubleSpinBox, self.spinBox_2)
        Dialog.setTabOrder(self.spinBox_2, self.doubleSpinBox_2)
        Dialog.setTabOrder(self.doubleSpinBox_2, self.doubleSpinBox_3)
        Dialog.setTabOrder(self.doubleSpinBox_3, self.doubleSpinBox_4)
        Dialog.setTabOrder(self.doubleSpinBox_4, self.comboBox_10)
        Dialog.setTabOrder(self.comboBox_10, self.comboBox_11)
        Dialog.setTabOrder(self.comboBox_11, self.comboBox_12)
        Dialog.setTabOrder(self.comboBox_12, self.doubleSpinBox_7)
        Dialog.setTabOrder(self.doubleSpinBox_7, self.comboBox_13)
        Dialog.setTabOrder(self.comboBox_13, self.comboBox_14)
        Dialog.setTabOrder(self.comboBox_14, self.doubleSpinBox_8)
        Dialog.setTabOrder(self.doubleSpinBox_8, self.comboBox_15)
        Dialog.setTabOrder(self.comboBox_15, self.lineEdit_3)
        Dialog.setTabOrder(self.lineEdit_3, self.pButton_Add)
        Dialog.setTabOrder(self.pButton_Add, self.pButton_Cancel)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Tuition Record"))
        self.label_23.setText(_translate("Dialog", "Choose Student:"))
        self.label_25.setText(_translate("Dialog", "&last name"))
        self.label_24.setText(_translate("Dialog", "first &name"))
        self.label.setText(_translate("Dialog", "student id"))
        self.label_2.setText(_translate("Dialog", "&unique tuition id"))
        self.label_4.setText(_translate("Dialog", "&tuition date"))
        self.label_6.setText(_translate("Dialog", "tuition wee&k day"))
        self.label_7.setText(_translate("Dialog", "start time"))
        self.label_8.setText(_translate("Dialog", "&duration"))
        self.label_9.setText(_translate("Dialog", "travel distance"))
        self.doubleSpinBox.setSuffix(_translate("Dialog", " miles"))
        self.label_10.setText(_translate("Dialog", "fees per hour"))
        self.spinBox_2.setPrefix(_translate("Dialog", "£ "))
        self.label_12.setText(_translate("Dialog", "travel cost"))
        self.doubleSpinBox_2.setPrefix(_translate("Dialog", "£ "))
        self.label_11.setText(_translate("Dialog", "website cost"))
        self.doubleSpinBox_3.setPrefix(_translate("Dialog", "£ "))
        self.label_13.setText(_translate("Dialog", "discount"))
        self.doubleSpinBox_4.setPrefix(_translate("Dialog", "£ "))
        self.label_26.setText(_translate("Dialog", "char&ge for travel"))
        self.label_27.setText(_translate("Dialog", "charge for website"))
        self.label_28.setText(_translate("Dialog", "travel method"))
        self.label_29.setText(_translate("Dialog", "transport ticket\n"
"price"))
        self.doubleSpinBox_7.setPrefix(_translate("Dialog", "£ "))
        self.label_30.setText(_translate("Dialog", "pa&yment method"))
        self.label_31.setText(_translate("Dialog", "payment received"))
        self.label_32.setText(_translate("Dialog", "payment amount\n"
"received"))
        self.doubleSpinBox_8.setPrefix(_translate("Dialog", "£ "))
        self.label_33.setText(_translate("Dialog", "receipt completed"))
        self.label_34.setText(_translate("Dialog", "invoice number"))
        self.totalCostLabel.setText(_translate("Dialog", "total cost"))
        self.pButton_Add_more.setText(_translate("Dialog", "Add more"))
        self.pButton_Add.setText(_translate("Dialog", "Add"))
        self.pButton_Cancel.setText(_translate("Dialog", "Cancel"))

