# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_add_schedule_entry.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(660, 500)
        Dialog.setMinimumSize(QtCore.QSize(660, 500))
        Dialog.setMaximumSize(QtCore.QSize(680, 500))
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 641, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_110 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_110.setFont(font)
        self.label_110.setObjectName("label_110")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_110)
        self.lcdNumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setObjectName("lcdNumber")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lcdNumber)
        self.label_130 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_130.setFont(font)
        self.label_130.setObjectName("label_130")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_130)
        self.comboBox_12 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_12.setFont(font)
        self.comboBox_12.setObjectName("comboBox_12")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_12)
        self.label_140 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_140.setFont(font)
        self.label_140.setObjectName("label_140")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_140)
        self.timeEdit = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timeEdit.setFont(font)
        self.timeEdit.setWrapping(False)
        self.timeEdit.setSpecialValueText("")
        self.timeEdit.setTime(QtCore.QTime(12, 0, 0))
        self.timeEdit.setObjectName("timeEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.timeEdit)
        self.label_150 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_150.setFont(font)
        self.label_150.setObjectName("label_150")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_150)
        self.spinBox_11 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_11.setFont(font)
        self.spinBox_11.setMaximum(300)
        self.spinBox_11.setSingleStep(30)
        self.spinBox_11.setProperty("value", 60)
        self.spinBox_11.setObjectName("spinBox_11")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBox_11)
        self.label_170 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_170.setFont(font)
        self.label_170.setObjectName("label_170")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_170)
        self.spinBox_12 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_12.setFont(font)
        self.spinBox_12.setSingleStep(5)
        self.spinBox_12.setProperty("value", 20)
        self.spinBox_12.setObjectName("spinBox_12")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBox_12)
        self.comboBox_11 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_11.setObjectName("comboBox_11")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_11)
        self.label_120 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_120.setObjectName("label_120")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_120)
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_13.setFont(font)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_13)
        self.label_210 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_210.setFont(font)
        self.label_210.setObjectName("label_210")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_210)
        self.horizontalLayout_2.addLayout(self.formLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setSpacing(6)
        self.formLayout_3.setObjectName("formLayout_3")
        self.comboBox_21 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_21.setFont(font)
        self.comboBox_21.setObjectName("comboBox_21")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_21)
        self.label_230 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_230.setFont(font)
        self.label_230.setObjectName("label_230")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_230)
        self.doubleSpinBox_21 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_21.setFont(font)
        self.doubleSpinBox_21.setObjectName("doubleSpinBox_21")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_21)
        self.label_250 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_250.setFont(font)
        self.label_250.setObjectName("label_250")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_250)
        self.doubleSpinBox_22 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_22.setFont(font)
        self.doubleSpinBox_22.setObjectName("doubleSpinBox_22")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_22)
        self.label_270 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_270.setFont(font)
        self.label_270.setObjectName("label_270")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_270)
        self.comboBox_24 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_24.setFont(font)
        self.comboBox_24.setObjectName("comboBox_24")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comboBox_24)
        self.label_220 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_220.setFont(font)
        self.label_220.setObjectName("label_220")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_220)
        self.comboBox_22 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_22.setFont(font)
        self.comboBox_22.setObjectName("comboBox_22")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_22)
        self.label_240 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_240.setFont(font)
        self.label_240.setObjectName("label_240")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_240)
        self.comboBox_23 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_23.setFont(font)
        self.comboBox_23.setObjectName("comboBox_23")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_23)
        self.label_260 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_260.setFont(font)
        self.label_260.setObjectName("label_260")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_260)
        self.horizontalLayout_2.addLayout(self.formLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.addressLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.addressLabel.setObjectName("addressLabel")
        self.horizontalLayout_4.addWidget(self.addressLabel)
        self.addressLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.addressLineEdit.setObjectName("addressLineEdit")
        self.horizontalLayout_4.addWidget(self.addressLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pButton_Add_more = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pButton_Add_more.setObjectName("pButton_Add_more")
        self.horizontalLayout.addWidget(self.pButton_Add_more)
        self.pButton_Add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pButton_Add.setFont(font)
        self.pButton_Add.setObjectName("pButton_Add")
        self.horizontalLayout.addWidget(self.pButton_Add)
        self.pButton_Cancel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pButton_Cancel.setFont(font)
        self.pButton_Cancel.setObjectName("pButton_Cancel")
        self.horizontalLayout.addWidget(self.pButton_Cancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_140.setBuddy(self.timeEdit)
        self.label_150.setBuddy(self.spinBox_11)
        self.label_170.setBuddy(self.spinBox_12)
        self.label_210.setBuddy(self.doubleSpinBox_13)
        self.label_230.setBuddy(self.doubleSpinBox_21)
        self.label_250.setBuddy(self.doubleSpinBox_22)
        self.label_270.setBuddy(self.comboBox_24)
        self.label_220.setBuddy(self.comboBox_21)
        self.label_240.setBuddy(self.comboBox_22)
        self.label_260.setBuddy(self.comboBox_24)

        self.retranslateUi(Dialog)
        self.pButton_Cancel.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.comboBox_11, self.comboBox_12)
        Dialog.setTabOrder(self.comboBox_12, self.timeEdit)
        Dialog.setTabOrder(self.timeEdit, self.spinBox_11)
        Dialog.setTabOrder(self.spinBox_11, self.spinBox_12)
        Dialog.setTabOrder(self.spinBox_12, self.doubleSpinBox_13)
        Dialog.setTabOrder(self.doubleSpinBox_13, self.comboBox_21)
        Dialog.setTabOrder(self.comboBox_21, self.doubleSpinBox_21)
        Dialog.setTabOrder(self.doubleSpinBox_21, self.comboBox_22)
        Dialog.setTabOrder(self.comboBox_22, self.doubleSpinBox_22)
        Dialog.setTabOrder(self.doubleSpinBox_22, self.comboBox_23)
        Dialog.setTabOrder(self.comboBox_23, self.comboBox_24)
        Dialog.setTabOrder(self.comboBox_24, self.addressLineEdit)
        Dialog.setTabOrder(self.addressLineEdit, self.pButton_Add_more)
        Dialog.setTabOrder(self.pButton_Add_more, self.pButton_Add)
        Dialog.setTabOrder(self.pButton_Add, self.pButton_Cancel)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Schedule Entry"))
        self.label_3.setText(_translate("Dialog", "Enter new appointment:"))
        self.label_110.setText(_translate("Dialog", "entry number"))
        self.label_130.setText(_translate("Dialog", "weekday"))
        self.label_140.setText(_translate("Dialog", "start time"))
        self.label_150.setText(_translate("Dialog", "duration"))
        self.label_170.setText(_translate("Dialog", "fees per hour"))
        self.spinBox_12.setPrefix(_translate("Dialog", "£ "))
        self.label_120.setText(_translate("Dialog", "student name"))
        self.doubleSpinBox_13.setPrefix(_translate("Dialog", "£ "))
        self.label_210.setText(_translate("Dialog", "discount"))
        self.label_230.setText(_translate("Dialog", "1st extra cost amount"))
        self.doubleSpinBox_21.setPrefix(_translate("Dialog", "£ "))
        self.label_250.setText(_translate("Dialog", "2nd extra cost amount"))
        self.doubleSpinBox_22.setPrefix(_translate("Dialog", "£ "))
        self.label_270.setText(_translate("Dialog", "travel method"))
        self.label_220.setText(_translate("Dialog", "1st extra cost type"))
        self.label_240.setText(_translate("Dialog", "2nd extra cost type"))
        self.label_260.setText(_translate("Dialog", "payment method"))
        self.addressLabel.setText(_translate("Dialog", "address"))
        self.pButton_Add_more.setText(_translate("Dialog", "Add more"))
        self.pButton_Add.setText(_translate("Dialog", "Add"))
        self.pButton_Cancel.setText(_translate("Dialog", "Cancel"))

