# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 649)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setSizeIncrement(QtCore.QSize(5, 5))
        self.centralwidget.setBaseSize(QtCore.QSize(800, 600))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.tabWidget.setSizeIncrement(QtCore.QSize(5, 5))
        self.tabWidget.setBaseSize(QtCore.QSize(800, 600))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setAccessibleName(_fromUtf8(""))
        self.tab_3.setAccessibleDescription(_fromUtf8(""))
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tableView_3 = QtGui.QTableView(self.tab_3)
        self.tableView_3.setGeometry(QtCore.QRect(0, 0, 791, 561))
        self.tableView_3.setObjectName(_fromUtf8("tableView_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tableView_4 = QtGui.QTableView(self.tab_4)
        self.tableView_4.setGeometry(QtCore.QRect(0, 0, 791, 561))
        self.tableView_4.setObjectName(_fromUtf8("tableView_4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tableView = QtGui.QTableView(self.tab)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 791, 561))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tableView_2 = QtGui.QTableView(self.tab_2)
        self.tableView_2.setGeometry(QtCore.QRect(0, 1, 791, 561))
        self.tableView_2.setObjectName(_fromUtf8("tableView_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tableView_5 = QtGui.QTableView(self.tab_5)
        self.tableView_5.setGeometry(QtCore.QRect(-5, 1, 801, 561))
        self.tableView_5.setObjectName(_fromUtf8("tableView_5"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menuEdit.setFont(font)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuAdd = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menuAdd.setFont(font)
        self.menuAdd.setObjectName(_fromUtf8("menuAdd"))
        self.menuDelete = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menuDelete.setFont(font)
        self.menuDelete.setObjectName(_fromUtf8("menuDelete"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menuHelp.setFont(font)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("quit"))
        self.actionQuit.setIcon(icon)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAdd_mileage = QtGui.QAction(MainWindow)
        self.actionAdd_mileage.setObjectName(_fromUtf8("actionAdd_mileage"))
        self.actionAdd_tuition_record = QtGui.QAction(MainWindow)
        self.actionAdd_tuition_record.setObjectName(_fromUtf8("actionAdd_tuition_record"))
        self.actionAdd_student_record = QtGui.QAction(MainWindow)
        self.actionAdd_student_record.setObjectName(_fromUtf8("actionAdd_student_record"))
        self.actionMileage_record = QtGui.QAction(MainWindow)
        self.actionMileage_record.setObjectName(_fromUtf8("actionMileage_record"))
        self.actionTuition_record = QtGui.QAction(MainWindow)
        self.actionTuition_record.setObjectName(_fromUtf8("actionTuition_record"))
        self.actionStudent_record = QtGui.QAction(MainWindow)
        self.actionStudent_record.setObjectName(_fromUtf8("actionStudent_record"))
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(MainWindow)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionSave_all = QtGui.QAction(MainWindow)
        self.actionSave_all.setObjectName(_fromUtf8("actionSave_all"))
        self.actionCommit_table = QtGui.QAction(MainWindow)
        self.actionCommit_table.setObjectName(_fromUtf8("actionCommit_table"))
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName(_fromUtf8("actionAbout_Qt"))
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addAction(self.actionCommit_table)
        self.menuFile.addAction(self.actionSave_all)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuAdd.addSeparator()
        self.menuAdd.addAction(self.actionAdd_mileage)
        self.menuAdd.addAction(self.actionAdd_tuition_record)
        self.menuAdd.addAction(self.actionAdd_student_record)
        self.menuDelete.addAction(self.actionMileage_record)
        self.menuDelete.addAction(self.actionTuition_record)
        self.menuDelete.addAction(self.actionStudent_record)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAdd.menuAction())
        self.menubar.addAction(self.menuDelete.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.tableView)
        MainWindow.setTabOrder(self.tableView, self.tableView_2)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "tuition records", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "invoice records", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "mileage records", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "student info", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "student counters", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuAdd.setTitle(_translate("MainWindow", "Add", None))
        self.menuDelete.setTitle(_translate("MainWindow", "Delete", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionAdd_mileage.setText(_translate("MainWindow", "mileage record", None))
        self.actionAdd_tuition_record.setText(_translate("MainWindow", "tuition record", None))
        self.actionAdd_student_record.setText(_translate("MainWindow", "student record", None))
        self.actionMileage_record.setText(_translate("MainWindow", "mileage record", None))
        self.actionTuition_record.setText(_translate("MainWindow", "tuition record", None))
        self.actionStudent_record.setText(_translate("MainWindow", "student record", None))
        self.actionCopy.setText(_translate("MainWindow", "Copy", None))
        self.actionCut.setText(_translate("MainWindow", "Cut", None))
        self.actionPaste.setText(_translate("MainWindow", "Paste", None))
        self.actionUndo.setText(_translate("MainWindow", "Undo", None))
        self.actionRedo.setText(_translate("MainWindow", "Redo", None))
        self.actionSave_all.setText(_translate("MainWindow", "commit all", None))
        self.actionCommit_table.setText(_translate("MainWindow", "commit table", None))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt", None))

