# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tuitionAdmin2.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1404, 735)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/general/icons/gnumeric.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setSizeIncrement(QtCore.QSize(5, 5))
        self.centralwidget.setBaseSize(QtCore.QSize(800, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.tabWidget.setSizeIncrement(QtCore.QSize(5, 5))
        self.tabWidget.setBaseSize(QtCore.QSize(800, 600))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setEnabled(True)
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.student_view = QtWidgets.QTableView(self.tab)
        self.student_view.setObjectName("student_view")
        self.student_view.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.student_view)
        self.tabWidget.addTab(self.tab, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stdcount_view = QtWidgets.QTableView(self.tab_6)
        self.stdcount_view.setObjectName("stdcount_view")
        self.horizontalLayout_2.addWidget(self.stdcount_view)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setMinimumSize(QtCore.QSize(792, 0))
        self.tab_1.setObjectName("tab_1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.schedule_view = QtWidgets.QTableView(self.tab_1)
        self.schedule_view.setEnabled(True)
        self.schedule_view.setObjectName("schedule_view")
        self.horizontalLayout_7.addWidget(self.schedule_view)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setAccessibleName("")
        self.tab_2.setAccessibleDescription("")
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tuition_view = QtWidgets.QTableView(self.tab_2)
        self.tuition_view.setObjectName("tuition_view")
        self.horizontalLayout_6.addWidget(self.tuition_view)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.invoice_view = QtWidgets.QTableView(self.tab_3)
        self.invoice_view.setObjectName("invoice_view")
        self.horizontalLayout_3.addWidget(self.invoice_view)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.reminder_view = QtWidgets.QTableView(self.tab_4)
        self.reminder_view.setObjectName("reminder_view")
        self.horizontalLayout_4.addWidget(self.reminder_view)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.mileage_view = QtWidgets.QTableView(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mileage_view.setFont(font)
        self.mileage_view.setObjectName("mileage_view")
        self.horizontalLayout_8.addWidget(self.mileage_view)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setEnabled(True)
        self.tab_5.setMinimumSize(QtCore.QSize(792, 566))
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.time_view = QtWidgets.QTableView(self.tab_5)
        self.time_view.setObjectName("time_view")
        self.horizontalLayout_5.addWidget(self.time_view)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1404, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menuEdit.setFont(font)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAdd = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menuAdd.setFont(font)
        self.menuAdd.setObjectName("menuAdd")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menuHelp.setFont(font)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/general/icons/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/general/icons/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon1)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAdd_tuition_record = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/general/icons/insert-table2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_tuition_record.setIcon(icon2)
        self.actionAdd_tuition_record.setObjectName("actionAdd_tuition_record")
        self.actionAdd_student_record = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/general/icons/list-resource-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_student_record.setIcon(icon3)
        self.actionAdd_student_record.setObjectName("actionAdd_student_record")
        self.actionTuition_record = QtWidgets.QAction(MainWindow)
        self.actionTuition_record.setObjectName("actionTuition_record")
        self.actionStudent_record = QtWidgets.QAction(MainWindow)
        self.actionStudent_record.setObjectName("actionStudent_record")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/general/icons/edit-copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon4)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/general/icons/edit-cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon5.addPixmap(QtGui.QPixmap(":/general/icons/edit-cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon5)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/general/icons/edit-paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPaste.setIcon(icon6)
        self.actionPaste.setObjectName("actionPaste")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/general/icons/edit-undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon7)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/general/icons/edit-redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon8)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCommit_all = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/general/icons/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCommit_all.setIcon(icon9)
        self.actionCommit_all.setObjectName("actionCommit_all")
        self.actionCommit_table = QtWidgets.QAction(MainWindow)
        self.actionCommit_table.setIcon(icon9)
        self.actionCommit_table.setObjectName("actionCommit_table")
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionDelete_row = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/general/icons/edit-table-delete-row.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionDelete_row.setIcon(icon10)
        self.actionDelete_row.setObjectName("actionDelete_row")
        self.actionAbout_tuitionAdmin = QtWidgets.QAction(MainWindow)
        self.actionAbout_tuitionAdmin.setObjectName("actionAbout_tuitionAdmin")
        self.actionEdit_invoice_counter = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionEdit_invoice_counter.setFont(font)
        self.actionEdit_invoice_counter.setObjectName("actionEdit_invoice_counter")
        self.actionCreate_invoice = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionCreate_invoice.setFont(font)
        self.actionCreate_invoice.setObjectName("actionCreate_invoice")
        self.actionSend_invoice = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/general/icons/invoice.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSend_invoice.setIcon(icon11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionSend_invoice.setFont(font)
        self.actionSend_invoice.setObjectName("actionSend_invoice")
        self.actionCreate_receipts = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionCreate_receipts.setFont(font)
        self.actionCreate_receipts.setObjectName("actionCreate_receipts")
        self.actionReload_table = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/general/icons/view-refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionReload_table.setIcon(icon12)
        self.actionReload_table.setObjectName("actionReload_table")
        self.actionReload_all = QtWidgets.QAction(MainWindow)
        self.actionReload_all.setIcon(icon12)
        self.actionReload_all.setObjectName("actionReload_all")
        self.actionAdd_row = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/general/icons/edit-table-insert-row-below.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_row.setIcon(icon13)
        self.actionAdd_row.setObjectName("actionAdd_row")
        self.actionAdd_scooter_mileage = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/general/icons/road2b.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_scooter_mileage.setIcon(icon14)
        self.actionAdd_scooter_mileage.setObjectName("actionAdd_scooter_mileage")
        self.actionDisplay_summary = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionDisplay_summary.setFont(font)
        self.actionDisplay_summary.setObjectName("actionDisplay_summary")
        self.actionTime_Recording = QtWidgets.QAction(MainWindow)
        self.actionTime_Recording.setCheckable(True)
        self.actionTime_Recording.setChecked(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionTime_Recording.setFont(font)
        self.actionTime_Recording.setObjectName("actionTime_Recording")
        self.actionShow_student_info = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/general/icons/xmag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_student_info.setIcon(icon15)
        self.actionShow_student_info.setObjectName("actionShow_student_info")
        self.actionShow_student_counters = QtWidgets.QAction(MainWindow)
        self.actionShow_student_counters.setIcon(icon15)
        self.actionShow_student_counters.setObjectName("actionShow_student_counters")
        self.actionShow_invoice_counter = QtWidgets.QAction(MainWindow)
        self.actionShow_invoice_counter.setIcon(icon15)
        self.actionShow_invoice_counter.setObjectName("actionShow_invoice_counter")
        self.actionAdd_schedule_entry = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/general/icons/add-calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_schedule_entry.setIcon(icon16)
        self.actionAdd_schedule_entry.setObjectName("actionAdd_schedule_entry")
        self.actionAdd_car_mileage = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/general/icons/road2c.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_car_mileage.setIcon(icon17)
        self.actionAdd_car_mileage.setObjectName("actionAdd_car_mileage")
        self.actionFilter_stdcounters = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/general/icons/filter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFilter_stdcounters.setIcon(icon18)
        self.actionFilter_stdcounters.setObjectName("actionFilter_stdcounters")
        self.actionCheck_records = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionCheck_records.setFont(font)
        self.actionCheck_records.setObjectName("actionCheck_records")
        self.actionSend_reminders = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionSend_reminders.setFont(font)
        self.actionSend_reminders.setObjectName("actionSend_reminders")
        self.actionMaking_Backups = QtWidgets.QAction(MainWindow)
        self.actionMaking_Backups.setCheckable(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionMaking_Backups.setFont(font)
        self.actionMaking_Backups.setObjectName("actionMaking_Backups")
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addAction(self.actionCommit_all)
        self.menuFile.addAction(self.actionReload_all)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuAdd.addSeparator()
        self.menuAdd.addAction(self.actionAdd_tuition_record)
        self.menuAdd.addAction(self.actionAdd_student_record)
        self.menuAdd.addAction(self.actionAdd_scooter_mileage)
        self.menuAdd.addAction(self.actionAdd_schedule_entry)
        self.menuAdd.addSeparator()
        self.menuAdd.addAction(self.actionDelete_row)
        self.menuAdd.addAction(self.actionAdd_row)
        self.menuAdd.addSeparator()
        self.menuAdd.addAction(self.actionShow_student_info)
        self.menuAdd.addAction(self.actionShow_student_counters)
        self.menuAdd.addAction(self.actionShow_invoice_counter)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuHelp.addAction(self.actionAbout_tuitionAdmin)
        self.menuTools.addAction(self.actionCreate_invoice)
        self.menuTools.addAction(self.actionCheck_records)
        self.menuTools.addAction(self.actionSend_invoice)
        self.menuTools.addAction(self.actionCreate_receipts)
        self.menuTools.addAction(self.actionDisplay_summary)
        self.menuTools.addAction(self.actionSend_reminders)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionTime_Recording)
        self.menuTools.addAction(self.actionMaking_Backups)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAdd.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionQuit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCommit_all)
        self.toolBar.addAction(self.actionReload_all)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAdd_tuition_record)
        self.toolBar.addAction(self.actionAdd_student_record)
        self.toolBar.addAction(self.actionAdd_car_mileage)
        self.toolBar.addAction(self.actionAdd_schedule_entry)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFilter_stdcounters)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(6)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TuitionAdmin"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "student info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "s-counters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "weekly schedule"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "tuition records"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "invoice records"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "reminder records"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "car mileage"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "time recording"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuAdd.setTitle(_translate("MainWindow", "Table"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAdd_tuition_record.setText(_translate("MainWindow", "Add tuition record"))
        self.actionAdd_student_record.setText(_translate("MainWindow", "Add student record"))
        self.actionTuition_record.setText(_translate("MainWindow", "tuition record"))
        self.actionStudent_record.setText(_translate("MainWindow", "student record"))
        self.actionCopy.setText(_translate("MainWindow", "&Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionCommit_all.setText(_translate("MainWindow", "Save"))
        self.actionCommit_all.setToolTip(_translate("MainWindow", "Save all tables"))
        self.actionCommit_all.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionCommit_table.setText(_translate("MainWindow", "Save table"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))
        self.actionDelete_row.setText(_translate("MainWindow", "Delete row"))
        self.actionAbout_tuitionAdmin.setText(_translate("MainWindow", "About tuitionAdmin"))
        self.actionEdit_invoice_counter.setText(_translate("MainWindow", "Edit invoice counter"))
        self.actionCreate_invoice.setText(_translate("MainWindow", "Dump Table"))
        self.actionCreate_invoice.setIconText(_translate("MainWindow", "Dump Table to Konsole"))
        self.actionCreate_invoice.setToolTip(_translate("MainWindow", "Dump Table to Konsole"))
        self.actionSend_invoice.setText(_translate("MainWindow", "Send invoice"))
        self.actionSend_invoice.setStatusTip(_translate("MainWindow", "test"))
        self.actionCreate_receipts.setText(_translate("MainWindow", "Create receipts"))
        self.actionReload_table.setText(_translate("MainWindow", "Reload table"))
        self.actionReload_all.setText(_translate("MainWindow", "Reload"))
        self.actionReload_all.setToolTip(_translate("MainWindow", "Reload all tables"))
        self.actionAdd_row.setText(_translate("MainWindow", "Add row"))
        self.actionAdd_row.setToolTip(_translate("MainWindow", "Add row at the end of the table"))
        self.actionAdd_scooter_mileage.setText(_translate("MainWindow", "Add scooter mileage"))
        self.actionAdd_scooter_mileage.setToolTip(_translate("MainWindow", "Add scooter mileage record"))
        self.actionDisplay_summary.setText(_translate("MainWindow", "Display summary"))
        self.actionTime_Recording.setText(_translate("MainWindow", "Time Recording"))
        self.actionShow_student_info.setText(_translate("MainWindow", "Show student info"))
        self.actionShow_student_counters.setText(_translate("MainWindow", "Show student counters"))
        self.actionShow_invoice_counter.setText(_translate("MainWindow", "Show invoice counter"))
        self.actionAdd_schedule_entry.setText(_translate("MainWindow", "Add schedule entry"))
        self.actionAdd_car_mileage.setText(_translate("MainWindow", "Add car mileage"))
        self.actionAdd_car_mileage.setToolTip(_translate("MainWindow", "Add car mileage record"))
        self.actionFilter_stdcounters.setText(_translate("MainWindow", "filter_stdcounters"))
        self.actionFilter_stdcounters.setToolTip(_translate("MainWindow", "filter out from student counters inactive students"))
        self.actionCheck_records.setText(_translate("MainWindow", "Check records"))
        self.actionSend_reminders.setText(_translate("MainWindow", "Send reminders"))
        self.actionMaking_Backups.setText(_translate("MainWindow", "Making Backups"))

import icons_rc
